Train card
joshbasden/TTRServer pull request #16
Opened 2019-03-27 20:29 UTC by bradley-hales

2019-03-27 23:27 UTC, joshbasden requested changes

2019-03-27 23:27 UTC, joshbasden commented on src/Command/ServerCommand/ClaimGrayCommand.java
> +    iRequest data;
This should be private.

2019-03-27 23:27 UTC, joshbasden commented on src/Model/Game.java
> +//                route.setPoints(routeJson.get("points").getAsInt());
This must be what was breaking joinGame... Not sure what I was thinking haha.

2019-03-27 23:27 UTC, joshbasden commented on json/Routes.json
> +    "lon1": 2155.0,
Shouldn't this be 2154.0?






jk

2019-03-27 23:27 UTC, joshbasden commented on src/Model/Model.java
> +        if (cards.size() == 5){
Shouldn't this always be 5? I'm not seeing why this would indicate there are 3 locomotives..

2019-03-27 23:27 UTC, joshbasden commented on src/Model/Game.java
> +            if (counter >= 2){
I think this would break if you replaced a locomotive with a locomotive. It there were two there already, and the next card was a locomotive, then this would return true, but you would want it to return false.

2019-03-27 23:27 UTC, joshbasden commented on src/Model/Game.java
> +            replaceAllFaceUp();
I don't think this recursion would work. You're not using the return statement from replaceAllFaceUp(). If the new 5 cards had 3 or more locomotives, then you would call the function again, but return the bad hand a few lines later. Replacing this with "return replaceAllFaceUp();" might fix it, but I would test it to make sure.

2019-03-27 23:27 UTC, joshbasden commented on src/Model/Model.java
> +            for (String oneUsername: usernamesOfPlayers) {
Why not use that beautiful function you wrote to add commands to all players in a game? :)

2019-03-27 23:27 UTC, joshbasden commented on src/Model/Model.java
> +        if (game.claimRoute(username, req.getId())) {
I thought the TAs said we had to let the user choose what color to use when it's gray. This would just assign a color to the route.

2019-03-27 23:30 UTC, joshbasden commented on src/Model/Game.java
> +//                route.setPoints(routeJson.get("points").getAsInt());
Actually I know what I was thinking but this was a really bad way to fix it. I'll figure it out later.

2019-03-28 01:20 UTC, bradley-hales commented on src/Model/Model.java
> +        if (cards.size() == 5){
If its 5 then I am replacing all the cards, otherwise it is 2 cards which is just replace one face up

2019-03-28 15:56 UTC, joshbasden commented on src/Model/Model.java
> +        if (cards.size() == 5){
Gotcha. Makes sense.

2019-03-28 19:06 UTC, joshbasden approved these changes
Still need to fix the issue in the needToReplaceAll method, but I'll merge it with master so we have an updated copy of the code.

2019-03-28 19:33 UTC, merged